### ISSUE TITLE
Add 'logbook' as a pip dependency

### ISSUE THREAD

**Issue by kcgen** [gzc/gitstats#1]
**pip install gitstats**

```
Collecting gitstats
  Downloading gitstats-0.2.4.tar.gz (4.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n6skr5h1/gitstats/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n6skr5h1/gitstats/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-n6skr5h1/gitstats/pip-egg-info
         cwd: /tmp/pip-install-n6skr5h1/gitstats/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n6skr5h1/gitstats/setup.py", line 5, in <module>
        import gitstats
      File "/tmp/pip-install-n6skr5h1/gitstats/gitstats/__init__.py", line 3, in <module>
        from logbook import Logger, StreamHandler
    ModuleNotFoundError: No module named 'logbook'
```

**Comment by kcgen** [comment]
Hmm - maybe the pip package is a different project? (closing).
